# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy package files and install all dependencies including devDependencies for building
COPY package*.json ./

RUN npm install

# Copy rest of the files
COPY . .

# Build the TypeScript source files
RUN npm run build

# Expose port if needed (optional)
# EXPOSE 3000

# Set the default command to start the MCP server
CMD [ "node", "dist/index.js" ]
